name: soundux
version: "0.2"
summary: A free and open source cross-platform soundboard
description: |
  Universal soundboard using pulseaudio modules

confinement: devmode
base: core20

parts:
  soundux:
    build-packages:
      - g++
      - make
      - xorg-dev
      - libx11-dev
      - libxi-dev
      - libwebkit2gtk-4.0-dev
    stage-packages:
      - libwebkit2gtk-4.0-37
      - pulseaudio
      - pulseaudio-utils
      - libxi6
      - libx11-6
    plugin: cmake
    cmake-generator: Ninja
    source-type: git
    source: https://github.com/Soundux/Soundux


apps:
  soundux:
    command: usr/local/bin/soundux
    plugs:
      - x11
      - desktop
      - desktop-legacy
      - home
      - alsa
      - pulseaudio
      - audio-playback
