name: soundux
version: "0.2.6"
summary: A free and open source cross-platform soundboard
description: |
  Universal soundboard using PulseAudio modules

confinement: classic
base: core20
architectures:
  - build-on: amd64
    run-on: amd64

parts:
  soundux:
    build-packages:
      - g++
      - make
      - xorg-dev
      - libx11-dev
      - libxi-dev
      - libwnck-3-dev
      - libappindicator3-dev
      - libwebkit2gtk-4.0-dev
      - libssl-dev
      - libpulse-dev
      - software-properties-common
    stage-packages:
      - libwebkit2gtk-4.0-37
      - libpulse0
      - libxi6
      - libwnck-3-0
      - libappindicator3-1
      - libx11-6
      - gvfs
      - ffmpeg
      - youtube-dl
    override-pull: |
      sudo add-apt-repository -y ppa:pipewire-debian/pipewire-upstream
      sudo apt install -y libpipewire-0.3-dev
      snapcraftctl pull

      # Point icon to the correct location
      sed -i -e 's|Icon=soundux|Icon=/usr/share/pixmaps/soundux.png|g' deployment/soundux.desktop
    plugin: cmake
    cmake-generator: Ninja
    source-type: git
    source-tag: 0.2.6
    source: https://github.com/Soundux/Soundux
    parse-info: [usr/share/metainfo/io.github.Soundux.metainfo.xml]

apps:
  soundux:
    command: opt/soundux/soundux
    desktop: usr/share/applications/soundux.desktop
    environment:
      GIO_MODULE_DIR: /snap/core20/current/lib/x86_64-linux-gnu/gio/modules
    #plugs:
    #  - x11
    #  - desktop
    #  - desktop-legacy
    #  - home
    #  - alsa
    #  - pulseaudio
    #  - audio-playback
    common-id: io.github.Soundux
